-- 코드를 입력하세요
SELECT
    A.CAR_ID,
    A.CAR_TYPE,
    FLOOR(A.DAILY_FEE * (1 - (P.DISCOUNT_RATE / 100)) * 30) AS FEE
FROM
    CAR_RENTAL_COMPANY_CAR A
JOIN
    CAR_RENTAL_COMPANY_DISCOUNT_PLAN P
      ON A.CAR_TYPE = P.CAR_TYPE AND P.DURATION_TYPE = '30일 이상'
LEFT JOIN
    CAR_RENTAL_COMPANY_RENTAL_HISTORY B
      ON B.CAR_ID = A.CAR_ID AND B.START_DATE <= '2022-11-30' AND B.END_DATE >= '2022-11-01'
WHERE
    A.CAR_TYPE IN ('세단','SUV')
    AND B.CAR_ID IS NULL 
    AND (A.DAILY_FEE * (1 - (P.DISCOUNT_RATE / 100)) * 30) BETWEEN 500000 AND 1999999
ORDER BY
    FEE DESC, A.CAR_TYPE ASC, A.CAR_ID DESC