SELECT 
    YEAR(SALES_DATE) YEAR,
    MONTH(SALES_DATE) MONTH,
    GENDER,
    COUNT(DISTINCT A.USER_ID) USERS
FROM
    ONLINE_SALE A
INNER JOIN
    USER_INFO B ON A.USER_ID=B.USER_ID
WHERE
    B.GENDER IS NOT NULL
GROUP BY
    YEAR(SALES_DATE), MONTH(SALES_DATE), GENDER
ORDER BY
    YEAR(SALES_DATE) ASC, MONTH(SALES_DATE) ASC, GENDER ASC