-- 코드를 입력하세요
SELECT
    YEAR(A.SALES_DATE) YEAR,
    MONTH(A.SALES_DATE) MONTH,
    COUNT(DISTINCT A.USER_ID) PURCHASED_USERS,
    ROUND(
        COUNT(DISTINCT A.USER_ID) / 
        (SELECT COUNT(*) FROM USER_INFO WHERE YEAR(JOINED) = 2021),1) PURCHASED_RATIO
FROM 
    ONLINE_SALE A
INNER JOIN
    USER_INFO B ON A.USER_ID = B.USER_ID
WHERE
    YEAR(B.JOINED) = 2021
GROUP BY
    YEAR(A.SALES_DATE), MONTH(A.SALES_DATE)
ORDER BY
    YEAR(A.SALES_DATE) ASC, MONTH(A.SALES_DATE) ASC    