-- 코드를 작성해주세요
SELECT
    B.YEAR YEAR	,
    B.MAX_SIZE - A.SIZE_OF_COLONY YEAR_DEV,
    A.ID ID
FROM
    ECOLI_DATA A
INNER JOIN
    (
    SELECT
        YEAR(DIFFERENTIATION_DATE) YEAR,
        MAX(SIZE_OF_COLONY) MAX_SIZE
    FROM
        ECOLI_DATA
    GROUP BY 
        YEAR
    ) B 
ON YEAR(A.DIFFERENTIATION_DATE) = B.YEAR
ORDER BY
    B.YEAR ASC, YEAR_DEV ASC