-- 코드를 입력하세요
SELECT
    B.TITLE,
    A.BOARD_ID,
    A.REPLY_ID,
    A.WRITER_ID,
    A.CONTENTS,
    TO_CHAR(A.CREATED_DATE, 'YYYY-MM-DD') AS CREATED_DATE
FROM
    USED_GOODS_REPLY A,
    USED_GOODS_BOARD B
WHERE
    A.BOARD_ID = B.BOARD_ID
    AND TO_CHAR(B.CREATED_DATE, 'YYYY-MM') = '2022-10'
ORDER BY
    A.CREATED_DATE ASC,B.TITLE ASC